### ISSUE TITLE
ocasionally get - Error: no open connections

### ISSUE THREAD

**Issue by henryoswald** [mafintosh/mongojs#130]
Hi occasionally we get a small rush of "Error: no open connections"

	Error: no open connections
	    at __executeQueryCommand (/myapp/node_modules/mongojs/node_modules/mongodb/lib/mongodb/db.js:1486:23)
	    at Db._executeQueryCommand (/myapp/node_modules/mongojs/node_modules/mongodb/lib/mongodb/db.js:1669:7)
	    at Cursor.nextObject (/myapp/node_modules/mongojs/node_modules/mongodb/lib/mongodb/cursor.js:674:13)
	    at /myapp/node_modules/mongojs/index.js:87:6

What is the best way to deal with this? Is it with ?maxPoolSize=200 ?

Thanks.

**Comment by asvaghasiya** [comment]
I am facing the same issue and yet to find the solution. Can anyone help me out?
