### ISSUE TITLE
Errors after upgrade to node 0.12.5

### ISSUE THREAD

**Issue by nuviad** [mafintosh/mongojs#215]
I upgraded my node.js to 0.12.5 and also updated my mongojs and started getting this error.
It seems that the connection method was changed to I changed it accordingly but still getting error:

/var/www/node_modules/mongodb-core/lib/topologies/server.js:807
      catch(err) { process.nextTick(function() { throw err}); }
                                                       ^
TypeError: undefined is not a function
    at /var/www//node_modules/mongojs/lib/collection.js:70:5
    at /var/www/node_modules/mongojs/lib/collection.js:166:7
    at /var/www/node_modules/mongodb-core/lib/topologies/server.js:806:13
    at Callbacks.emit (/var/www/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/var/www/node_modules/mongodb-core/lib/topologies/server.js:246:23)
    at Socket.<anonymous> (/var/www/node_modules/mongodb-core/lib/connection/connection.js:259:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

Any idea?

**Comment by saintedlama** [comment]
The connect function is currently not supported but you can use `mongojs(connectionString, [collections] ` instead. 

Could you post the source code that yields the above error?

**Comment by goldfire** [comment]
I'm seeing the same issue when using `mongojs` and trying to listen for an error event on it (in the exact same way as shown in the documentation).

**Comment by saintedlama** [comment]
Event listening has been fixed in version 1.3.x
