### ISSUE TITLE
Could not login using mongojs

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [mafintosh/mongojs#234]
Hi,I have a login application.I am getting the proper data inside post method but unable to call the callback functions.It also throwing the below error.

```
db.on('ready', function () {
   ^
TypeError: Object Oditek has no method 'on'
    at Object.<anonymous> (C:\Documents and Settings\Subhrajyoti\Desktop\Restore
\htdocs\video broadcast\server.js:19:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```
I am explaining my code below.

server.js

```
var port=8888;
var express=require('express');
var morgan = require('morgan');
var http=require('http');
var bodyParser= require('body-parser');
var methodOverride = require('method-override');
var mongo = require('mongojs');
var database='Oditek';
var collections=['video'];
var app= express();
var server=http.createServer(app);
var io=require('socket.io')(server);
var db = mongo("127.0.0.1:27017/"+database, collections);
app.use(express.static(__dirname + '/public'));     // set the static files location /public/img will be /img for users
app.use(morgan('dev'));                     // log every request to the console
app.use(bodyParser.urlencoded({ extended: false }))    // parse application/x-www-form-urlencoded
app.use(bodyParser.json())    // parse application/json
app.use(methodOverride());                  // simulate DELETE and PUT
db.on('ready', function () {
    console.log('database connected')
});
app.get('/',function(req,res){
	res.sendfile('view/login.html');
});
app.post('/login',function(req,res){
	var username=req.body.username;
	var password=req.body.userpassword;
	if(username && password){
		db.video.findOne({
			username:username,
			password:password
		},function(err,doc){
			console.log('login',doc);
			if(doc){
			res.send(doc);
			}
			if(err){
				console.log('login',err);
				res.send("could not login");
			}
		});
	}
});
app.get('/video',function(req,res){
	res.sendfile('view/video.html');
});
server.listen(port);
console.log('server is listening on the port'+port);
```
In this above file the console part is not executing at all.i am explaining package.json file below.
```
{
  "name": "oditek",
  "main": "server.js",
  "dependencies": {
    "express": "~4.0.0",
    "morgan": "~1.0.0",
    "body-parser": "~1.0.0",
    "method-override": "~1.0.0",
	"socket.io":"1.3.5",
	"mongojs": "1.2.1"
  }
}
```

Please help me to resolve this issue as well as error soon.

**Comment by goldfire** [comment]
I am seeing the same issue when trying to listen for the `error` event on the initial DB connection.

**Comment by revitalkeren** [comment]
experienced the same issues.
downgraded to version v0.18.2 - works as it should.
I also saw there was a comment in the latest commits regarding events not working , should be fixed in the next release (I believe there's already a pull request fixing it)...
