### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by tiefenb** [mafintosh/mongojs#246]
I get often an error and can't find a solution. It happens in the mongodb-core module...

2015-09-08T06:15:02.883564+00:00 app[worker.1]: /app/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/server.js:757
2015-09-08T06:15:02.883591+00:00 app[worker.1]:       catch(err) { process.nextTick(function() { throw err}); }
2015-09-08T06:15:02.883593+00:00 app[worker.1]:                                                  ^
2015-09-08T06:15:02.883595+00:00 app[worker.1]: 
2015-09-08T06:15:02.883596+00:00 app[worker.1]: TypeError: cb is not a function
2015-09-08T06:15:02.883598+00:00 app[worker.1]:     at /app/node_modules/mongojs/lib/collection.js:131:7
2015-09-08T06:15:02.883599+00:00 app[worker.1]:     at /app/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/replset.js:371:5
2015-09-08T06:15:02.883601+00:00 app[worker.1]:     at /app/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/server.js:756:13
2015-09-08T06:15:02.883602+00:00 app[worker.1]:     at Callbacks.emit (/app/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/server.js:95:3)
2015-09-08T06:15:02.883604+00:00 app[worker.1]:     at null.messageHandler (/app/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/server.js:243:23)
2015-09-08T06:15:02.883606+00:00 app[worker.1]:     at Socket.<anonymous> (/app/node_modules/mongojs/node_modules/mongodb-core/lib/connection/connection.js:262:22)
2015-09-08T06:15:02.883608+00:00 app[worker.1]:     at emitOne (events.js:77:13)
2015-09-08T06:15:02.883609+00:00 app[worker.1]:     at Socket.emit (events.js:169:7)
2015-09-08T06:15:02.883610+00:00 app[worker.1]:     at readableAddChunk (_stream_readable.js:146:16)
2015-09-08T06:15:02.883612+00:00 app[worker.1]:     at Socket.Readable.push (_stream_readable.js:110:10)
2015-09-08T06:15:02.883613+00:00 app[worker.1]:     at TCP.onread (net.js:523:20)

**Comment by tiefenb** [comment]
found the bug, callback was missing in my script in .remove function.... added a empty function

**Comment by upendraksingh** [comment]
please share how you have added empty callback function

**Comment by chriwup** [comment]
I got the same error following [those tutorials](http://thejackalofjavascript.com/mapreduce-in-mongodb/), and pinpointed the problem to this line:

```
db.sourceData.mapReduce(
	mapper,
	reducer,
	{
		out : "example2_results"
	}
 ); 
```

As it is, you get the following error:

```
catch(err) { process.nextTick(function() { throw err}); }
                                                 ^

TypeError: cb is not a function
    at /Users/christophebenoit1/code/meteor-test/mapreduce/node_modules/mongojs/lib/collection.js:167:7
    at /Users/christophebenoit1/code/meteor-test/mapreduce/node_modules/mongodb-core/lib/topologies/server.js:765:13
    at Callbacks.emit (/Users/christophebenoit1/code/meteor-test/mapreduce/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/Users/christophebenoit1/code/meteor-test/mapreduce/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/Users/christophebenoit1/code/meteor-test/mapreduce/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
``` 

Once a callback function is added as 4th parameter of mapReduce(), no exception shows up:

```
db.sourceData.mapReduce(
        mapper,
        reducer,
        {
                out : "example2_results"
        },
        function () { }
 );
```

The documentation says this parameter is optional so to me this is a bug. Please reopen this ticket.

Using mongojs@1.4.1.

**Comment by inidaname** [comment]
this is still a problem please

**Comment by melsayed91** [comment]
still the problem found in the latest version without a solution
