### ISSUE TITLE
db.close() issue when connecting to  MONGOLAB  URI

### ISSUE THREAD

**Issue by ibreakoutx** [mafintosh/mongojs#247]
When I run the following code, with a local mongo instance, everything works.
```javascript
var mongojs = require('mongojs');

// connect now, and worry about collections later
var connection = process.env.MONGOLAB_URI || 'mongoldb://localhost/test' ;

var db = mongojs(connection);
console.log("connection = " + connection);

var objcollection = db.collection("pets");

objcollection.find({}, function(err,docs) {
    console.log(docs);
    db.close();
    console.log("db.close() finished");
});
```
### Output
>>connection = mongodb://localhost/test
docs printout fine
db.close() finished

*When I run the same code, connecting to a MONGOLAB URI, I get*

>>connection = heroku_user:heroku_passwd@ds035643.mongolab.com:35643/heroku_user
docs printout fine.
db.close() finished
/Users/jack/projects/kokowantsahome/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:247
      throw err;
            ^
TypeError: undefined is not a function
    at /Users/jack/projects/kokowantsahome/node_modules/mongojs/lib/database.js:66:12
    at apply (/Users/jack/projects/kokowantsahome/node_modules/mongojs/node_modules/thunky/index.js:16:28)
    at null._getServer (/Users/jack/projects/kokowantsahome/node_modules/mongojs/node_modules/thunky/index.js:27:3)
    at Database.close (/Users/jack/projects/kokowantsahome/node_modules/mongojs/lib/database.js:64:8)
    at /Users/jack/projects/kokowantsahome/try_mongojs.js:19:8
    at /Users/jack/projects/kokowantsahome/node_modules/mongojs/lib/cursor.js:59:24
    at handleCallback (/Users/jack/projects/kokowantsahome/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:244:5)
    at setCursorDeadAndNotified (/Users/jack/projects/kokowantsahome/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:548:3)
    at nextFunction (/Users/jack/projects/kokowantsahome/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:718:7)
    at Cursor.next (/Users/ack/projects/kokowantsahome/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:749:3)

**Also with the official mongodb driver, I don't see this issue**

**Comment by ibreakoutx** [comment]
The find command itself seems to have executed fine, I get the error when I do the db.close().
of course, without a db.close() the script will just hang.

**Comment by ibreakoutx** [comment]
Discontinued use of mongojs and just stuck with the native (& officially supported) mongodb driver.

**Comment by 5an1ty** [comment]
Open this issue again please, it's not only a problem with mongolab... The close method crashes and this should be fixed.
