### ISSUE TITLE
Callback undefined making error on bulk.execute

### ISSUE THREAD

**Issue by wallynm** [mafintosh/mongojs#263]
If you try to make a bulk exec without pass a cb function, it returns a error. 
Just check if cb it's defined

```
  var date = new Date();
  date.setMinutes(date.getMinutes() - 1);
 
 authBulk.find({timestamp: {$lt:date}}).remove();
 authBulk.execute();
```

Error: 
```JAVASCRIPT
 undefined is not a function
    at /Users/wallysson/www/connect-proxy/node_modules/mongojs/lib/bulk.js:159:7
    at loop (/Users/wallysson/www/connect-proxy/node_modules/mongojs/node_modules/each-series/index.js:10:33)
    at process._tickCallback (node.js:355:11)
```

**Comment by saintedlama** [comment]
Fixed in git - version 2.0.1 to come soon. You could just use

```js
authBulk.execute(function() { });
```
as a workaround
