### ISSUE TITLE
Cannot figure out this error

### ISSUE THREAD

**Issue by davidwieler** [mafintosh/mongojs#292]
Using the most recent version, 2.3.0

`
/node_modules/mongojs/node_modules/mongodb/lib/mongodb/mongo_client.js:409
          throw err
                ^
Error: connection closed
    at null.<anonymous> (/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:607:24)
    at emit (events.js:104:17)
    at null.<anonymous> (/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:171:15)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection.js:550:12)
    at Socket.emit (events.js:107:17)
    at TCP.close (net.js:485:12)
`

**Comment by olegam** [comment]
Well it looks like a connection error, but if you expect someone to be able to help you, you should probably provide a little more information and context. What are you trying to do? Give a short code example that triggers the error etc.
