### ISSUE TITLE
arrayFilter support

### ISSUE THREAD

**Issue by gustawdaniel** [mafintosh/mongojs#347]
Basing on docs about new mongo 3.6 feature - $[]:

> https://docs.mongodb.com/manual/reference/operator/update/positional-all/#up._S_[]

I wrote mongo update query:

```
db.users.update({_id:"iPCLJQAD7i9Lrvs4p"},{$set:{"profile.stock.$[currency].address": 4000}},{arrayFilters: [{"currency.code":"ETH"}]})
```

It works great in mongo shell console, but using js:

```
Meteor.users._collection.rawCollection().update({_id: "iPCLJQAD7i9Lrvs4p"},{$set:{"profile.stock.$[c].address": 4000}},{arrayFilters: [{"c.code": 'ETH'}]}
```

I have got error.

```
MongoError: No array filter found for identifier 'c' in path 'profile.stock.$[c].address'
I20180215-18:05:57.745(1)?     at Function.MongoError.create (/home/daniel/.meteor/packages/npm-mongo/.2.2.34.1gs2ze4.93eul++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
I20180215-18:05:57.745(1)?     at toError (/home/daniel/.meteor/packages/npm-mongo/.2.2.34.1gs2ze4.93eul++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:139:22)
I20180215-18:05:57.745(1)?     at /home/daniel/.meteor/packages/npm-mongo/.2.2.34.1gs2ze4.93eul++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/collection.js:1059:67
I20180215-18:05:57.746(1)?     at /home/daniel/.meteor/packages/npm-mongo/.2.2.34.1gs2ze4.93eul++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:469:18
I20180215-18:05:57.746(1)?     at _combinedTickCallback (internal/process/next_tick.js:131:7)
I20180215-18:05:57.746(1)?     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
I20180215-18:05:57.746(1)?      name: 'MongoError',
I20180215-18:05:57.746(1)?      message: 'No array filter found for identifier \'c\' in path \'profile.stock.$[c].address\'',
I20180215-18:05:57.746(1)?      driver: true,
I20180215-18:05:57.747(1)?      index: 0,
I20180215-18:05:57.747(1)?      code: 2,
I20180215-18:05:57.747(1)?      errmsg: 'No array filter found for identifier \'c\' in path \'profile.stock.$[c].address\''
```

Is `arrayFilters` option supported as option in Mongo update query in this library?

**Comment by gustawdaniel** [comment]
I found article about this:

> http://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-array-filters.html

It looks like rather Meteor problem with update of his packages than mongojs problem.

> Using array filters with Node.js requires versions >= 3.0.0 of the MongoDB Node.js driver or >= 5.0.0 of mongoose in addition to v3.6 of the MongoDB server. Earlier versions of the MongoDB (2.x) and mongoose (4.x) do not support array filters.
