### ISSUE TITLE
Getting frequent Error: no open connections and Error: connection closed during heavy concurrent load

### ISSUE THREAD

**Issue by asvaghasiya** [mafintosh/mongojs#355]
I am facing the same issue and yet to find the solution. Can anyone help me out?
We are using MongoDB version 3.2.20, node 6.11 and MongoDB NPM 1.4.28.
MongoDB and Node are in different EC2 instances.

**Comment by asvaghasiya** [comment]
Logs from socket server:
```
DB Error V2RP :  Error: connection closed
    at .<anonymous> (/home/game/node_modules/mongodb/lib/mongodb/connection/server.js:617:45)
    at emitNone (events.js:86:13)
    at emit (events.js:185:7)
    at .<anonymous> (/home/game/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:165:15)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/home/game/node_modules/mongodb/lib/mongodb/connection/connection.js:550:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at CallbackStore.<anonymous> (/home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9)
    at CallbackStore.g (events.js:292:16)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: failed to connect to [xxx.xx.xxx.xxx:27017]
    at .<anonymous> (/home/game/node_modules/mongodb/lib/mongodb/connection/server.js:555:25)
    at emitThree (events.js:116:13)
    at emit (events.js:194:7)
    at .<anonymous> (/home/game/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/home/game/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:343:10)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at CallbackStore.<anonymous> (/home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9)
    at CallbackStore.g (events.js:292:16)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error V2RP :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at rec (/home/game/classes/dashboard.class.js:1446:144)
    at /home/game/classes/dashboard.class.js:1457:41
    at /home/game/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at commandHandler (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:693:48)
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
DB Error MP pit :  Error: no open connections
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:23)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)
    at Cursor.nextObject (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
    at Cursor.toArray (/home/game/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at /home/game/classes/profile.class.js:508:144
    at /home/game/node_modules/mongodb/lib/mongodb/collection/commands.js:54:20
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1170:22
    at /home/game/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at __executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1719:14)
    at Db._executeQueryCommand (/home/game/node_modules/mongodb/lib/mongodb/db.js:1881:7)

```
